name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Kaggle CLI
        run: pip install kaggle
      - name: Get dog breeds classification model
        run: kaggle kernels output nguyenbnguyen/dog-breed-classification-mobilenet -p ./ml_models/dog-breeds
      - name: List all
        run: ls ml_models -R
